version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - unused
    - misspell
    - ineffassign
    - dupl
    - goconst
  settings:
    misspell:
      locale: US
    dupl:
      threshold: 150
    goconst:
      min-len: 2
      min-occurrences: 3
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/klauern
