version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - unused
    - misspell
    - ineffassign
  settings:
    misspell:
      locale: US
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/klauern
