version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - unused
    - misspell
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  misspell:
    locale: US

formatters-settings:
  goimports:
    local-prefixes: github.com/klauern

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
