# Taskfile.yml for Clash Royale API project
# Requires: https://taskfile.dev/installation/

version: '3'

vars:
  PYTHON_VERSION: '3.11'
  PROJECT_NAME: clash-royale-api
  DATA_DIR: data
  TEST_PLAYER_TAG: '#R8QGUQRCV'
  GO_DIR: go
  CR_API_BIN: '{{.GO_DIR}}/bin/cr-api'
  DECKBUILDER_BIN: '{{.GO_DIR}}/bin/deckbuilder'

env:
  PYTHONPATH: './src'

dotenv: ['.env']

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Set up the development environment
    cmds:
      - echo "Setting up development environment..."
      - uv sync
      - task: build-go
      - echo "Creating data directories..."
      - mkdir -p {{.DATA_DIR}}/{players,clans,analysis,static,reference}
      - mkdir -p scripts
      - echo "Copying example .env file..."
      - test -f .env || cp config/.env.example .env 2>/dev/null || echo "No .env.example found, creating basic .env"
      - test -f .env || echo -e "CLASH_ROYALE_API_TOKEN=your_api_token_here\nDATA_DIR={{.DATA_DIR}}" > .env
      - echo "✅ Setup complete!"
      - echo "Please edit .env file with your API token"

  install:
    desc: Install dependencies and build Go binaries
    cmds:
      - uv sync
      - task: build-go

  build-go:
    desc: Build Go CLI binaries
    dir: go
    cmds:
      - echo "Building Go binaries..."
      - mkdir -p bin
      - go mod download
      - go build -o bin/cr-api ./cmd/cr-api
      - go build -o bin/deckbuilder ./cmd/deckbuilder
      - echo "✅ Go binaries built successfully!"
      - ls -la bin/

  run:
    desc: Analyze a player's collection using the Go CLI
    summary: |
      Analyze a player's card collection and display upgrade needs using the Go binary

      Args:
        player: Player tag to analyze (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        CLEAN_TAG="${PLAYER_TAG#\#}"
        echo "Analyzing $CLEAN_TAG with Go CLI..."
        {{.CR_API_BIN}} analyze --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}"
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  run-with-save:
    desc: Run Go CLI analysis and save results to JSON files
    summary: |
      Analyze a player and save the results to JSON files using the Go binary

      Args:
        player: Player tag to analyze (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        CLEAN_TAG="${PLAYER_TAG#\#}"
        echo "Analyzing and saving results for $CLEAN_TAG..."
        {{.CR_API_BIN}} analyze --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --save
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  export-csv:
    desc: Export player and reference data to CSV using the Go CLI
    summary: |
      Export player's card collection and other data to CSV using the Go binary

      Args:
        player: Player tag to analyze (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        CLEAN_TAG="${PLAYER_TAG#\#}"
        echo "Exporting player data for $CLEAN_TAG to CSV..."
        {{.CR_API_BIN}} player --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --export-csv --save

        echo "Exporting card database to CSV..."
        {{.CR_API_BIN}} cards --data-dir "{{.DATA_DIR}}" --export-csv
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  export-all:
    desc: Export all available data types for a player using the Go CLI
    summary: |
      Export player data, card database, and save analysis results using the Go binary

      Args:
        player: Player tag to analyze (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        CLEAN_TAG="${PLAYER_TAG#\#}"
        echo "Exporting full dataset for $CLEAN_TAG..."
        {{.CR_API_BIN}} player --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --chests --export-csv --save
        {{.CR_API_BIN}} cards --data-dir "{{.DATA_DIR}}" --export-csv
        {{.CR_API_BIN}} analyze --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --save
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  build-deck:
    desc: Build an optimized 1v1 ladder deck from the latest analysis using Go binaries
    summary: |
      Runs card analysis (saved) and then builds a recommended 1v1 ladder deck.

      Args:
        player: Player tag to use (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        CLEAN_TAG="${PLAYER_TAG#\#}"

        echo "Running analysis for $CLEAN_TAG..."
        {{.CR_API_BIN}} analyze --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --save

        ANALYSIS_FILE="{{.DATA_DIR}}/analysis/${PLAYER_TAG}.json"
        if [ ! -f "$ANALYSIS_FILE" ]; then
          echo "Expected analysis file not found at $ANALYSIS_FILE" >&2
          exit 1
        fi

        echo "Building optimized 1v1 deck from latest analysis..."
        {{.DECKBUILDER_BIN}} -tag "$CLEAN_TAG" -data-dir "{{.DATA_DIR}}" -analysis-file "$ANALYSIS_FILE"
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"
      - sh: test -x {{.DECKBUILDER_BIN}}
        msg: "deckbuilder binary not found. Build it with: task build-go"

  # Event Deck Tasks
  scan-events:
    desc: Scan battle logs for event decks using Go CLI
    summary: |
      Automatically scan and import event decks from battle logs using the Go binary

      Args:
        player: Player tag to scan (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
        days: Number of days to scan back (default: 7)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        # Extract days from end of args if present, otherwise use default
        DAYS="{{.DAYS_BACK}}"

        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        # Remove any surrounding quotes from PLAYER_TAG
        CLEAN_TAG=$(echo "$PLAYER_TAG" | sed "s/^'//;s/'$//" | sed 's/^"//;s/"$//')
        CLEAN_TAG="${CLEAN_TAG#\#}"

        echo "Scanning event decks for $CLEAN_TAG (last $DAYS days)..."
        {{.CR_API_BIN}} events scan --tag "$CLEAN_TAG" --days "$DAYS" --data-dir "{{.DATA_DIR}}" --save
    vars:
      DAYS_BACK:
        sh: "echo '{{.ARGS}}' | grep -oE '[0-9]+$' || echo '7'"
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  export-events:
    desc: Export event decks to CSV using Go CLI
    summary: |
      Export event decks with performance data to CSV using the Go binary

      Args:
        player: Player tag to export (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        # Remove any surrounding quotes from PLAYER_TAG
        CLEAN_TAG=$(echo "$PLAYER_TAG" | sed "s/^'//;s/'$//" | sed 's/^"//;s/"$//')
        CLEAN_TAG="${CLEAN_TAG#\#}"

        echo "Exporting event decks for $CLEAN_TAG to CSV..."
        {{.CR_API_BIN}} events list --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --export-csv
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  export-decks:
    desc: Export event decks in deck builder format using Go CLI
    summary: |
      Export event decks for sharing on deck builder sites using the Go binary

      Args:
        player: Player tag to export (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        # Remove any surrounding quotes from PLAYER_TAG
        CLEAN_TAG=$(echo "$PLAYER_TAG" | sed "s/^'//;s/'$//" | sed 's/^"//;s/"$//')
        CLEAN_TAG="${CLEAN_TAG#\#}"

        echo "Exporting event decks for $CLEAN_TAG in deck builder format..."
        # Note: The Go CLI doesn't have a specific deck builder export yet,
        # so we'll export the event list which can be used for deck building
        {{.CR_API_BIN}} events list --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --export-csv
        echo "Deck builder format exported to CSV - can be imported into deck building sites"
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  analyze-events:
    desc: Analyze event deck performance using Go CLI
    summary: |
      Analyze event deck performance with detailed insights using the Go binary

      Args:
        player: Player tag to analyze (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        # Remove any surrounding quotes from PLAYER_TAG
        CLEAN_TAG=$(echo "$PLAYER_TAG" | sed "s/^'//;s/'$//" | sed 's/^"//;s/"$//')
        CLEAN_TAG="${CLEAN_TAG#\#}"

        echo "Analyzing event performance for $CLEAN_TAG..."
        {{.CR_API_BIN}} events analyze --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --min-battles 5 --export-csv
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  sync-events:
    desc: Sync recent event activity using Go CLI
    summary: |
      Sync and analyze recent event activity from battle logs using the Go binary

      Args:
        player: Player tag to sync (optional, will use DEFAULT_PLAYER_TAG from .env if not provided)
    cmds:
      - |
        PLAYER_TAG="{{.CLI_ARGS}}"
        if [ -z "$PLAYER_TAG" ]; then
          PLAYER_TAG="${DEFAULT_PLAYER_TAG}"
        fi

        if [ -z "$PLAYER_TAG" ]; then
          echo "Please provide a player tag or set DEFAULT_PLAYER_TAG in .env" >&2
          exit 1
        fi

        # Remove any surrounding quotes from PLAYER_TAG
        CLEAN_TAG=$(echo "$PLAYER_TAG" | sed "s/^'//;s/'$//" | sed 's/^"//;s/"$//')
        CLEAN_TAG="${CLEAN_TAG#\#}"

        echo "Syncing recent events for $CLEAN_TAG (last 7 days)..."
        {{.CR_API_BIN}} events scan --tag "$CLEAN_TAG" --data-dir "{{.DATA_DIR}}" --days 7 --save
        echo "Sync complete! Use 'task analyze-events -- $CLEAN_TAG' to analyze the data."
    preconditions:
      - sh: test -x {{.CR_API_BIN}}
        msg: "cr-api binary not found. Build it with: task build-go"

  test:
    desc: Run tests (both Go and Python)
    summary: |
      Run all tests for the project.
      - Go tests: Run all Go package tests with coverage
      - Python tests: Run existing Python tests (legacy)
    cmds:
      - echo "Running Go tests..."
      - |
        cd go && \
        if [ -f "../.env" ]; then
          # Export only valid variable names from .env (skip lines with # or invalid names)
          set -a
          while IFS='=' read -r key value; do
            # Skip lines starting with #, empty lines, or keys with invalid characters
            if [[ ! "$key" =~ ^[[:space:]]*# ]] && [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
              export "$key=$value"
            fi
          done < ../.env
          set +a
        fi && \
        go test -v -race -coverprofile=coverage.out ./... 2>/dev/null || go test -v ./...
      - echo "Running Python tests (legacy)..."
      - uv run pytest tests/ -x || true

  lint:
    desc: Run linting on the code (Go and Python)
    summary: |
      Run linters on both Go and Python code
      - Go: go vet and golint if available
      - Python: ruff for Python code (legacy)
    cmds:
      - echo "Running Go linter..."
      - cd go && go vet ./...
      - echo "Running Python linter (legacy)..."
      - uv run ruff check src/ || true

  format:
    desc: Format the code (Go and Python)
    summary: |
      Format both Go and Python code
      - Go: go fmt and goimports if available
      - Python: black and ruff for Python code (legacy)
    cmds:
      - echo "Formatting Go code..."
      - cd go && go fmt ./...
      - echo "Formatting Python code (legacy)..."
      - uv run black src/ 2>/dev/null || echo "black not available, skipping Python formatting"
      - uv run ruff check --fix src/ 2>/dev/null || echo "ruff not available, skipping Python fixes"

  clean:
    desc: Clean up generated files
    cmds:
      - echo "Cleaning up..."
      - rm -rf {{.DATA_DIR}}/
      - rm -rf __pycache__/
      - rm -rf src/__pycache__/
      - rm -rf src/*/__pycache__/
      - find . -name '*.pyc' -delete
      - echo "✅ Clean complete!"

  status:
    desc: Show project status
    cmds:
      - 'echo "=== Project Status ==="'
      - 'echo "Python version: {{.PYTHON_VERSION}}"'
      - 'echo "Project name: {{.PROJECT_NAME}}"'
      - 'echo "Data directory: {{.DATA_DIR}}"'
      - echo ''
      - 'echo "=== Environment ==="'
      - 'test -f .env && echo "✅ .env file exists" || echo "❌ .env file missing"'
      - 'test -f .env && grep -q "CLASH_ROYALE_API_TOKEN=" .env && echo "✅ API token configured" || echo "❌ API token not configured"'

  dev:
    desc: Start development mode with watch
    summary: |
      Watch for file changes and auto-format on save
      Requires: watchdog (installed with dev dependencies)
    cmds:
      - echo "Starting development mode..."
      - uv run python scripts/watch_dev.py

  test-go:
    desc: Run Go tests only
    summary: |
      Run Go tests with coverage and race detection
    cmds:
      - echo "Running Go tests..."
      - |
        cd go && \
        if [ -f "../.env" ]; then
          # Export only valid variable names from .env (skip lines with # or invalid names)
          set -a
          while IFS='=' read -r key value; do
            # Skip lines starting with #, empty lines, or keys with invalid characters
            if [[ ! "$key" =~ ^[[:space:]]*# ]] && [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
              export "$key=$value"
            fi
          done < ../.env
          set +a
        fi && \
        go test -v -race -coverprofile=coverage.out ./... 2>/dev/null || go test -v ./...
      - cd go && go tool cover -func=coverage.out | tail -1 || echo "Coverage report not available"
    preconditions:
      - sh: test -d go
        msg: "Go directory not found"

help-api:
    desc: Show API usage examples (Go CLI)
    cmds:
      - echo "Clash Royale API - Go CLI Usage Examples:"
      - echo "=========================================="
      - echo ''
      - echo "Prerequisites:"
      - 'echo "1. Build binaries: task build-go"'
      - 'echo "2. Set CLASH_ROYALE_API_TOKEN in .env file"'
      - echo ''
      - echo "Basic Player Operations:"
      - 'echo "1. Basic player analysis: task run -- #PLAYER_TAG"'
      - 'echo "2. Save results: task run-with-save -- #PLAYER_TAG"'
      - 'echo "3. Export to CSV: task export-csv -- #PLAYER_TAG"'
      - 'echo "4. Export all data: task export-all -- #PLAYER_TAG"'
      - 'echo "5. Build optimized deck: task build-deck -- #PLAYER_TAG"'
      - echo ''
      - echo "Event Deck Operations (using Go CLI):"
      - 'echo "6. Scan for event decks: task scan-events -- #PLAYER_TAG"'
      - 'echo "7. Export event decks: task export-events -- #PLAYER_TAG"'
      - 'echo "8. Export deck builder format: task export-decks -- #PLAYER_TAG"'
      - 'echo "9. Analyze events: task analyze-events -- #PLAYER_TAG"'
      - 'echo "10. Sync recent events: task sync-events -- #PLAYER_TAG"'
      - echo ''
      - echo "Development Commands:"
      - 'echo "- Build: task build-go"'
      - 'echo "- Test all: task test (runs Go tests + Python legacy tests)"'
      - 'echo "- Test Go only: task test-go"'
      - 'echo "- Lint: task lint (Go vet + Python ruff)"'
      - 'echo "- Format: task format (go fmt + Python black/ruff)"'
      - echo ''
      - 'echo "Replace #PLAYER_TAG with actual tag (e.g., '#R8QGUQRCV')"'
      - 'echo "Note: All tasks now use Go binaries instead of Python"'
